version: 2
updates:
  - package-ecosystem: pip
    directory: /backend
    target-branch: dev
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /frontend
    target-branch: dev
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /e2e
    target-branch: dev
    schedule:
      interval: weekly
