/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Patch User */
        patch: operations["patch_user_api_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create the first user. Returns 409 if any users already exist (use admin panel instead).
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/setup-required": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Setup Required
         * @description Returns true if no users exist yet — used to trigger the first-run setup page.
         */
        get: operations["setup_required_api_auth_setup_required_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cardio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cardio */
        get: operations["list_cardio_api_cardio_get"];
        put?: never;
        /** Log Cardio */
        post: operations["log_cardio_api_cardio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cardio/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activities */
        get: operations["list_activities_api_cardio_activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cardio/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Cardio */
        delete: operations["delete_cardio_api_cardio__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_api_exercises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_exercises_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise */
        get: operations["get_exercise_api_exercises__exercise_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Features */
        get: operations["get_features_api_features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gdpr/erase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Erase My Data */
        delete: operations["erase_my_data_api_gdpr_erase_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gdpr/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export My Data */
        get: operations["export_my_data_api_gdpr_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Logs */
        get: operations["get_logs_api_logs_get"];
        put?: never;
        /** Log Set */
        post: operations["log_set_api_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/last/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Last Set */
        get: operations["get_last_set_api_logs_last__exercise_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/measurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Measurements */
        get: operations["list_measurements_api_measurements_get"];
        put?: never;
        /** Log Measurement */
        post: operations["log_measurement_api_measurements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/measurements/{measurement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Measurement */
        delete: operations["delete_measurement_api_measurements__measurement_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Profile */
        patch: operations["patch_profile_api_profile_patch"];
        trace?: never;
    };
    "/api/progress/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Muscle Balance */
        get: operations["muscle_balance_api_progress_balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/consistency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consistency */
        get: operations["consistency_api_progress_consistency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/prs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personal Records */
        get: operations["personal_records_api_progress_prs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/strength": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strength Progression */
        get: operations["strength_progression_api_progress_strength_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Volume Over Time */
        get: operations["volume_over_time_api_progress_volume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scale/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange */
        post: operations["exchange_api_scale_exchange_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Start Session */
        post: operations["start_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** End Session */
        patch: operations["end_session_api_sessions__session_id__end_patch"];
        trace?: never;
    };
    "/api/sessions/{session_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Logs */
        get: operations["get_session_logs_api_sessions__session_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home Stats */
        get: operations["home_stats_api_stats_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CardioEntryOut */
        CardioEntryOut: {
            /** Activity */
            activity: string;
            /** Distance M */
            distance_m: number | null;
            /** Duration S */
            duration_s: number | null;
            /** Id */
            id: number;
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
            /** Notes */
            notes: string | null;
        };
        /** CardioIn */
        CardioIn: {
            /** Activity */
            activity: string;
            /** Distance M */
            distance_m?: number | null;
            /** Duration S */
            duration_s?: number | null;
            /** Logged At */
            logged_at?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** CardioPage */
        CardioPage: {
            /** Items */
            items: components["schemas"]["CardioEntryOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** ConsistencyDay */
        ConsistencyDay: {
            /** Date */
            date: string;
            /** Session */
            session?: string | null;
            /** Trained */
            trained: boolean;
            /** Volume Kg */
            volume_kg?: number | null;
        };
        /** ConsistencyWeek */
        ConsistencyWeek: {
            /** Days */
            days: components["schemas"]["ConsistencyDay"][];
            /** Week */
            week: string;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** ExchangeIn */
        ExchangeIn: {
            /** Frames */
            frames?: string[];
            /**
             * Phone Seq
             * @default 0
             */
            phone_seq: number;
            /**
             * Sequence Sent
             * @default false
             */
            sequence_sent: boolean;
            /**
             * Utc Offset Min
             * @default 0
             */
            utc_offset_min: number;
        };
        /** ExchangeOut */
        ExchangeOut: {
            /** Error */
            error?: string | null;
            measurement?: components["schemas"]["MeasurementOut"] | null;
            /** Phone Seq */
            phone_seq: number;
            /** Send */
            send: string[];
            /** Sequence Sent */
            sequence_sent: boolean;
        };
        /** ExerciseOut */
        ExerciseOut: {
            /** Equip */
            equip: string;
            /** Id */
            id: number;
            /** Muscles */
            muscles: string | null;
            /** Name */
            name: string;
            /** Position */
            position: number;
            /** Session */
            session: string;
            /** Type */
            type: string;
        };
        /**
         * FeaturesOut
         * @description Optional features this instance has switched on (#326).
         *
         *     The frontend asks once, rather than probing feature endpoints for 404s.
         */
        FeaturesOut: {
            /** Scale */
            scale: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HomeStats */
        HomeStats: {
            /** Prev Week Volume */
            prev_week_volume: number;
            /** Streak */
            streak: number;
            /** Week Minutes */
            week_minutes: number;
            /** Week Volume */
            week_volume: number;
            /** Week Workouts */
            week_workouts: number;
        };
        /** LogOut */
        LogOut: {
            /** Exercise Id */
            exercise_id: number;
            /** Id */
            id: number;
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
            /** Reps */
            reps: number;
            /** Session Id */
            session_id: number;
            /** Weight */
            weight: number;
        };
        /** LogRequest */
        LogRequest: {
            /** Exercise Id */
            exercise_id: number;
            /** Reps */
            reps: number;
            /** Session Id */
            session_id: number;
            /** Weight */
            weight: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** MeasurementIn */
        MeasurementIn: {
            /** Bmi */
            bmi?: number | null;
            /** Bmr Kcal */
            bmr_kcal?: number | null;
            /** Body Age */
            body_age?: number | null;
            /** Body Fat Pct */
            body_fat_pct?: number | null;
            /** Body Water Pct */
            body_water_pct?: number | null;
            /** Fat Free Weight Kg */
            fat_free_weight_kg?: number | null;
            /** Fat Mass Kg */
            fat_mass_kg?: number | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Inorganic Salt Kg */
            inorganic_salt_kg?: number | null;
            /** La Fat Kg */
            la_fat_kg?: number | null;
            /** La Muscle Kg */
            la_muscle_kg?: number | null;
            /** La Z100 */
            la_z100?: number | null;
            /** La Z20 */
            la_z20?: number | null;
            /** Lean Mass Kg */
            lean_mass_kg?: number | null;
            /** Ll Fat Kg */
            ll_fat_kg?: number | null;
            /** Ll Muscle Kg */
            ll_muscle_kg?: number | null;
            /** Ll Z100 */
            ll_z100?: number | null;
            /** Ll Z20 */
            ll_z20?: number | null;
            /** Notes */
            notes?: string | null;
            /** Protein Kg */
            protein_kg?: number | null;
            /** Ra Fat Kg */
            ra_fat_kg?: number | null;
            /** Ra Muscle Kg */
            ra_muscle_kg?: number | null;
            /** Ra Z100 */
            ra_z100?: number | null;
            /** Ra Z20 */
            ra_z20?: number | null;
            /** Recorded At */
            recorded_at?: string | null;
            /** Rl Fat Kg */
            rl_fat_kg?: number | null;
            /** Rl Muscle Kg */
            rl_muscle_kg?: number | null;
            /** Rl Z100 */
            rl_z100?: number | null;
            /** Rl Z20 */
            rl_z20?: number | null;
            /** Skeletal Muscle Kg */
            skeletal_muscle_kg?: number | null;
            /** Smi */
            smi?: number | null;
            /** Subcutaneous Fat Pct */
            subcutaneous_fat_pct?: number | null;
            /** Trunk Fat Kg */
            trunk_fat_kg?: number | null;
            /** Trunk Muscle Kg */
            trunk_muscle_kg?: number | null;
            /** Trunk Z100 */
            trunk_z100?: number | null;
            /** Trunk Z20 */
            trunk_z20?: number | null;
            /** User Age */
            user_age?: number | null;
            /** User Sex */
            user_sex?: number | null;
            /** Visceral Fat Grade */
            visceral_fat_grade?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Whr Estimate */
            whr_estimate?: number | null;
        };
        /** MeasurementOut */
        MeasurementOut: {
            /** Bmi */
            bmi?: number | null;
            /** Bmr Kcal */
            bmr_kcal?: number | null;
            /** Body Age */
            body_age?: number | null;
            /** Body Fat Pct */
            body_fat_pct?: number | null;
            /** Body Water Pct */
            body_water_pct?: number | null;
            /** Fat Free Weight Kg */
            fat_free_weight_kg?: number | null;
            /** Fat Mass Kg */
            fat_mass_kg?: number | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Id */
            id: number;
            /** Inorganic Salt Kg */
            inorganic_salt_kg?: number | null;
            /** La Fat Kg */
            la_fat_kg?: number | null;
            /** La Muscle Kg */
            la_muscle_kg?: number | null;
            /** La Z100 */
            la_z100?: number | null;
            /** La Z20 */
            la_z20?: number | null;
            /** Lean Mass Kg */
            lean_mass_kg?: number | null;
            /** Ll Fat Kg */
            ll_fat_kg?: number | null;
            /** Ll Muscle Kg */
            ll_muscle_kg?: number | null;
            /** Ll Z100 */
            ll_z100?: number | null;
            /** Ll Z20 */
            ll_z20?: number | null;
            /** Notes */
            notes?: string | null;
            /** Protein Kg */
            protein_kg?: number | null;
            /** Ra Fat Kg */
            ra_fat_kg?: number | null;
            /** Ra Muscle Kg */
            ra_muscle_kg?: number | null;
            /** Ra Z100 */
            ra_z100?: number | null;
            /** Ra Z20 */
            ra_z20?: number | null;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Rl Fat Kg */
            rl_fat_kg?: number | null;
            /** Rl Muscle Kg */
            rl_muscle_kg?: number | null;
            /** Rl Z100 */
            rl_z100?: number | null;
            /** Rl Z20 */
            rl_z20?: number | null;
            /** Skeletal Muscle Kg */
            skeletal_muscle_kg?: number | null;
            /** Smi */
            smi?: number | null;
            /** Subcutaneous Fat Pct */
            subcutaneous_fat_pct?: number | null;
            /** Trunk Fat Kg */
            trunk_fat_kg?: number | null;
            /** Trunk Muscle Kg */
            trunk_muscle_kg?: number | null;
            /** Trunk Z100 */
            trunk_z100?: number | null;
            /** Trunk Z20 */
            trunk_z20?: number | null;
            /** Visceral Fat Grade */
            visceral_fat_grade?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Whr Estimate */
            whr_estimate?: number | null;
        };
        /** MeasurementPage */
        MeasurementPage: {
            /** Items */
            items: components["schemas"]["MeasurementOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** MuscleBalance */
        MuscleBalance: {
            /** Muscle */
            muscle: string;
            /** Percentage */
            percentage: number;
        };
        /** PatchUserRequest */
        PatchUserRequest: {
            /** Is Active */
            is_active?: boolean | null;
            /** Is Admin */
            is_admin?: boolean | null;
        };
        /** PersonalRecord */
        PersonalRecord: {
            /** Date */
            date: string;
            /** Estimated 1Rm */
            estimated_1rm: number;
            /** Exercise Id */
            exercise_id: number;
            /** Exercise Name */
            exercise_name: string;
            /** Reps */
            reps: number;
            /** Weight */
            weight: number;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Birth Year */
            birth_year: number | null;
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string | null;
            /** Height Cm */
            height_cm: number | null;
            /** Is Admin */
            is_admin: boolean;
            /** Sex */
            sex: string | null;
            /** Username */
            username: string;
        };
        /** ProfilePatch */
        ProfilePatch: {
            /** Birth Year */
            birth_year?: number | null;
            /** Display Name */
            display_name?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Sex */
            sex?: ("male" | "female" | "other") | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Consent Given
             * @constant
             */
            consent_given: true;
            /** Display Name */
            display_name?: string | null;
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** SessionLogEntry */
        SessionLogEntry: {
            /** Exercise Id */
            exercise_id: number;
            /** Exercise Name */
            exercise_name: string;
            /** Id */
            id: number;
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
            /** Reps */
            reps: number;
            /** Weight */
            weight: number;
        };
        /** SetupRequired */
        SetupRequired: {
            /** Required */
            required: boolean;
        };
        /** StartSessionRequest */
        StartSessionRequest: {
            /** Session */
            session: string;
        };
        /** StrengthData */
        StrengthData: {
            /** Data */
            data: components["schemas"]["StrengthPoint"][];
            /** Exercise Id */
            exercise_id: number;
            /** Exercise Name */
            exercise_name: string;
        };
        /** StrengthPoint */
        StrengthPoint: {
            /** Date */
            date: string;
            /** Estimated 1Rm */
            estimated_1rm: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string | null;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Is Admin */
            is_admin: boolean;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VolumePoint */
        VolumePoint: {
            /** Volume Kg */
            volume_kg: number;
            /** Week */
            week: string;
        };
        /** WorkoutSessionOut */
        WorkoutSessionOut: {
            /** Ended At */
            ended_at: string | null;
            /** Id */
            id: number;
            /** Session */
            session: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** WorkoutSessionSummary */
        WorkoutSessionSummary: {
            /** Ended At */
            ended_at: string | null;
            /** Id */
            id: number;
            /** Session */
            session: string;
            /** Set Count */
            set_count: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Volume Kg */
            volume_kg: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_user_api_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_user_api_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_required_api_auth_setup_required_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupRequired"];
                };
            };
        };
    };
    list_cardio_api_cardio_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardioPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_cardio_api_cardio_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardioIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardioEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activities_api_cardio_activities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    delete_cardio_api_cardio__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exercises_api_exercises_get: {
        parameters: {
            query?: {
                session?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_exercises_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_exercise_api_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_features_api_features_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturesOut"];
                };
            };
        };
    };
    erase_my_data_api_gdpr_erase_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export_my_data_api_gdpr_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_logs_api_logs_get: {
        parameters: {
            query: {
                exercise_id: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_set_api_logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_last_set_api_logs_last__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_measurements_api_measurements_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_measurement_api_measurements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeasurementIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_measurement_api_measurements__measurement_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measurement_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    patch_profile_api_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    muscle_balance_api_progress_balance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MuscleBalance"][];
                };
            };
        };
    };
    consistency_api_progress_consistency_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsistencyWeek"][];
                };
            };
        };
    };
    personal_records_api_progress_prs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalRecord"][];
                };
            };
        };
    };
    strength_progression_api_progress_strength_get: {
        parameters: {
            query: {
                exercise_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrengthData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volume_over_time_api_progress_volume_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumePoint"][];
                };
            };
        };
    };
    exchange_api_scale_exchange_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionSummary"][];
                };
            };
        };
    };
    start_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_api_sessions__session_id__end_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_logs_api_sessions__session_id__logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionLogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    home_stats_api_stats_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeStats"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
